services:
  backend:
    build: ./
    container_name: enefit-backend
    image: enefitbackend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/enefit_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db
  enefit-frontend:
    container_name: enefit-frontend
    image: enefitfrontend
    # build: ./
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080/
    depends_on:
      - backend
  db:
    image: postgres:latest
    container_name: enefit_db_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=enefit_db
    ports:
      - "5432:5432"
volumes:
  db_data: {}
